[versions]

junitjupiter = "5.8.1"
junitplatform = "1.10.3"
junit = "4.13.2"
jetbrains_annotations = "24.0.1"
autoservice = "1.0.1"

groovy = "4.0.23"
asm = "9.6"

fabric_loom = "1.5.6"
fabric_loader = "0.15.4"

tinyremapper = "0.10.0"

mixin = "0.8.5"

managedversioning = "1.2.21"

[libraries]

junit_api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitjupiter" }
junit_engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitjupiter" }
junit_console = { module = "org.junit.platform:junit-platform-console", version.ref = "junitplatform" }
junit_junit = { module = "junit:junit", version.ref = "junit" }

jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }

groovy_core = { module = "org.apache.groovy:groovy", version.ref = "groovy" }

asm_core = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm_commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm_tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }

fabric_loom = { module = "net.fabricmc:fabric-loom", version.ref = "fabric_loom" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_loader_junit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabric_loader" }
fabric_tinyremapper = { module = "net.fabricmc:tiny-remapper", version.ref = "tinyremapper" }

mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }

[plugins]

managedversioning = { id = "dev.lukebemish.managedversioning", version.ref = "managedversioning" }
